### ISSUE TITLE
Retrieve LDAP memberOf property

### ISSUE THREAD

**Issue by adjiandov** [univention/openid-connect-provider#8]
Hello, 
I have currently installed UCS and the OpenId connect provider app. The UCS is connected to a LDAP server and retrieves the users from there.
I am trying to setup oidc authentication through the oidc provider. Basic authentication/login is possible, but I need to get the user's groups/memberOf property from the UserInfo.

Is this possible and if yes how can this be done?
Thank you

**Comment by edamrose** [comment]
The current OpenID connect provider app does not support configuring the attributes that can be requested / transmitted. We are currently working on a new App, based on Keycloak, which will allow more configuration options.

**Comment by adjiandov** [comment]
Great to hear, just as a rough estimation, when can we expect this new app? Our approach was to put Keycloak on top of Univention if this is not supported, but if this new app comes soon maybe we can wait for it. Could you tell me more about the app?
